'use client';

import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import { motion } from "framer-motion";

const newsItems = [
  {
    title: "New 'Chrono-Wiper' Malware Targets Financial Institutions",
    date: "October 26, 2023",
    summary: "A sophisticated malware strain is actively targeting global financial networks, using novel techniques to evade detection...",
  },
  {
    title: "AI-Powered Phishing Scams on the Rise, FBI Warns",
    date: "October 24, 2023",
    summary: "The FBI has issued a warning about a new wave of highly convincing phishing emails generated by AI, making them harder to spot.",
  },
  {
    title: "Zero-Day Vulnerability Found in Popular Web Framework",
    date: "October 22, 2023",
    summary: "A critical zero-day vulnerability has been discovered in a widely-used web development framework. A patch is urgently needed.",
  },
];

export default function NewsFeed() {
  return (
    <section id="news" className="py-20 sm:py-32 bg-secondary/20">
      <div className="container max-w-screen-2xl">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Latest Cyber News</h2>
          <p className="mt-4 text-lg text-muted-foreground">Stay informed on the evolving landscape of digital security.</p>
        </div>
        <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
          {newsItems.map((item) => (
            <Card key={item.title} className="flex flex-col glassmorphic">
              <CardHeader>
                <CardTitle>{item.title}</CardTitle>
                <CardDescription>{item.date}</CardDescription>
              </CardHeader>
              <CardContent className="flex-grow">
                <p className="text-muted-foreground">{item.summary}</p>
              </CardContent>
              <CardFooter>
                <Button variant="outline" className="w-full">
                  Read More
                  <motion.div
                    animate={{ translateX: [0, 3, 0] }}
                    transition={{ duration: 1.5, repeat: Infinity, repeatType: "loop" }}
                  >
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </motion.div>
                </Button>
              </CardFooter>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
